### ISSUE TITLE
Mixin support

### ISSUE THREAD

**Issue by mrrpmrreeoow** [RosepadMC/RML#1]
When you start minecraft, minecraft will not start immediately, but RML will check [mixin](https://github.com/SpongePowered/Mixin)s, and when [mixin](https://github.com/SpongePowered/Mixin)s were present, RML will inject [mixin](https://github.com/SpongePowered/Mixin)s to Minecraft, and then Minecraft will start.
(= basic [mixin](https://github.com/SpongePowered/Mixin) support)

**Comment by TheAwesome98-Real** [comment]
awesome idea, this would make mod development very easy, but why do you link [mixin](https://github.com/SpongePowered/Mixin) every time you say it

**Comment by 5GameMaker** [comment]
I guess I need to clarify that RML is specifically the mod library. Mixin support will be added once I'll manage to make Rosepad Loader work (which includes stuff like patching vanilla jar)

**Comment by mrrpmrreeoow** [comment]
> awesome idea, this would make mod development very easy, but why do you link [mixin](https://github.com/SpongePowered/Mixin) every time you say it

idk why im linking it xDDD
